package gateway

const (
	httpScheme  = "http"
	httpsScheme = "https"

	healthRoute  = "GET /healthz"
	readyRoute   = "GET /readyz"
	metricsRoute = "GET /metrics"
	proxyRoute   = "/v1/"

	headerRequestID           = "X-Request-ID"
	headerRetryAfter          = "Retry-After"
	headerRouteReason         = "X-FishMesh-Route-Reason"
	headerSessionKey          = "X-FishMesh-Session-Key"
	headerRoutingMode         = "X-FishMesh-Routing-Mode"
	headerBackendID           = "X-FishMesh-Backend-ID"
	headerPreferredBackendID  = "X-FishMesh-Preferred-Backend-ID"
	headerPolicy              = "X-FishMesh-Policy"
	headerSpilloverReason     = "X-FishMesh-Spillover-Reason"
	headerKVStatus            = "X-FishMesh-KV-Status"
	headerCachedPrefixTokens  = "X-FishMesh-Cached-Prefix-Tokens"
	headerPromptTokens        = "X-FishMesh-Prompt-Tokens"
	headerUncachedTokens      = "X-FishMesh-Uncached-Tokens"
	headerEstimatedTTFTMS     = "X-FishMesh-Estimated-TTFT-Ms"
	headerEstimatorValid      = "X-FishMesh-Estimator-Valid"
	headerEstimatorConfidence = "X-FishMesh-Estimator-Confidence"
	headerEstimatorVersion    = "X-FishMesh-Estimator-Version"
	headerEstimatorReason     = "X-FishMesh-Estimator-Reason"
	headerLoadValid           = "X-FishMesh-Load-Valid"
	headerLoadSampleAgeMS     = "X-FishMesh-Load-Sample-Age-Ms"
	headerQueueDepth          = "X-FishMesh-Queue-Depth"
	headerRunningRequests     = "X-FishMesh-Running-Requests"
	headerLocalDelta          = "X-FishMesh-Local-Delta"
	headerLocalInflight       = "X-FishMesh-Local-Inflight"
	headerHardOverloadCount   = "X-FishMesh-Hard-Overload-Candidates"
	headerUpstream            = "X-FishMesh-Upstream"
	headerConnection          = "Connection"
	headerKeepAlive           = "Keep-Alive"
	headerProxyAuthenticate   = "Proxy-Authenticate"
	headerProxyAuthorization  = "Proxy-Authorization"
	headerTE                  = "Te"
	headerTrailer             = "Trailer"
	headerTransferEncoding    = "Transfer-Encoding"
	headerUpgrade             = "Upgrade"

	connectionClose    = "close"
	retryAfterSeconds  = "1"
	serviceBackendID   = "service"
	statusClientClosed = 499
	streamBufferBytes  = 32 * 1024
	requestIDBytes     = 16
	sseDataPrefix      = "data:"
	sseTerminalData    = "[DONE]"
)
