apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fishmesh-system
configMapGenerator:
  - name: fishmesh-epp-config
    files:
      - epp-config.yaml
generatorOptions:
  disableNameSuffixHash: true
