package config

const (
	envListenAddress               = "FISHMESH_LISTEN_ADDRESS"
	envUpstreamURL                 = "FISHMESH_UPSTREAM_URL"
	envRoutingMode                 = "FISHMESH_ROUTING_MODE"
	envKVAwareModel                = "FISHMESH_KV_AWARE_MODEL"
	envKVAwareRenderURL            = "FISHMESH_KV_AWARE_RENDER_URL"
	envKVAwareQueueTokenPenalty    = "FISHMESH_KV_AWARE_QUEUE_TOKEN_PENALTY"
	envKVAwareRunningTokenPenalty  = "FISHMESH_KV_AWARE_RUNNING_TOKEN_PENALTY"
	envKVAwareInflightTokenPenalty = "FISHMESH_KV_AWARE_INFLIGHT_TOKEN_PENALTY"
	envKVAwareEstimatorMode        = "FISHMESH_KV_AWARE_ESTIMATOR_MODE"
	envKVAwareStaticProfileFile    = "FISHMESH_KV_AWARE_STATIC_PROFILE_FILE"
	envPredictionMode              = "FISHMESH_PREDICTION_MODE"
	envBackendEndpoints            = "FISHMESH_BACKEND_ENDPOINTS"
	envEndpointDiscovery           = "FISHMESH_ENDPOINT_DISCOVERY"
	envEndpointService             = "FISHMESH_ENDPOINT_SERVICE"
	envEndpointNamespace           = "FISHMESH_ENDPOINT_NAMESPACE"
	envKubernetesAPIURL            = "FISHMESH_KUBERNETES_API_URL"
	envKubernetesTokenFile         = "FISHMESH_KUBERNETES_TOKEN_FILE"
	envKubernetesCAFile            = "FISHMESH_KUBERNETES_CA_FILE"
	envEndpointRefreshInterval     = "FISHMESH_ENDPOINT_REFRESH_INTERVAL"
	envEndpointMaxAge              = "FISHMESH_ENDPOINT_MAX_AGE"
	envObservationMode             = "FISHMESH_BACKEND_OBSERVATION_MODE"
	envObservationInterval         = "FISHMESH_BACKEND_OBSERVATION_INTERVAL"
	envObservationMaxAge           = "FISHMESH_BACKEND_OBSERVATION_MAX_AGE"
	envObservationRequestTimeout   = "FISHMESH_BACKEND_OBSERVATION_REQUEST_TIMEOUT"
	envKVAwareHardQueueDepth       = "FISHMESH_KV_AWARE_HARD_QUEUE_DEPTH"
	envKVAwareHardLocalInflight    = "FISHMESH_KV_AWARE_HARD_LOCAL_INFLIGHT"
	envUpstreamKeepAlive           = "FISHMESH_UPSTREAM_KEEPALIVE"
	envRequestTimeout              = "FISHMESH_REQUEST_TIMEOUT"
	envMaxRequestBodyBytes         = "FISHMESH_MAX_REQUEST_BODY_BYTES"
	envShutdownTimeout             = "FISHMESH_SHUTDOWN_TIMEOUT"
	envSessionKeyTTL               = "FISHMESH_SESSION_KEY_TTL"
	envSessionKeyMaxEntries        = "FISHMESH_SESSION_KEY_MAX_ENTRIES"
	envSessionKeyInflightDelta     = "FISHMESH_SESSION_KEY_INFLIGHT_DELTA"
	envSessionKeyQueueDepthDelta   = "FISHMESH_SESSION_KEY_QUEUE_DEPTH_DELTA"
	envMaxInflightRequests         = "FISHMESH_MAX_INFLIGHT_REQUESTS"
	envMaxConnsPerHost             = "FISHMESH_MAX_CONNS_PER_HOST"
	envCircuitEWMAAlpha            = "FISHMESH_CIRCUIT_EWMA_ALPHA"
	envCircuitErrorThreshold       = "FISHMESH_CIRCUIT_ERROR_THRESHOLD"
	envCircuitMinimumRequests      = "FISHMESH_CIRCUIT_MIN_REQUESTS"
	envCircuitOpenDuration         = "FISHMESH_CIRCUIT_OPEN_DURATION"
)
